import {
  InteractionResponseType,
  InteractionType,
  verifySignature,
} from "https://deno.land/x/discord_interactions@0.1.1/mod.ts";

const TOKEN = Deno.env.get("DISCORD_BOT_TOKEN");
const PUBLIC_KEY = Deno.env.get("DISCORD_PUBLIC_KEY");
const ALLOWED_ROLE = Deno.env.get("ALLOWED_ROLE_ID"); // role restriction

Deno.serve(async (req) => {
  const signature = req.headers.get("x-signature-ed25519")!;
  const timestamp = req.headers.get("x-signature-timestamp")!;
  const body = await req.text();

  const valid = await verifySignature({
    body,
    signature,
    timestamp,
    publicKey: PUBLIC_KEY!,
  });

  if (!valid) {
    return new Response("Invalid request signature", { status: 401 });
  }

  const json = JSON.parse(body);

  // Ping event
  if (json.type === InteractionType.PING) {
    return Response.json({ type: InteractionResponseType.PONG });
  }

  // Slash command
  if (json.type === InteractionType.APPLICATION_COMMAND) {
    const command = json.data.name;
    const userRoles = json.member.roles;

    // Check role
    if (!userRoles.includes(ALLOWED_ROLE)) {
      return Response.json({
        type: InteractionResponseType.CHANNEL_MESSAGE_WITH_SOURCE,
        data: {
          content: "❌ You do not have permission to use this command.",
          flags: 64, // ephemeral
        },
      });
    }

    if (command === "embed") {
      return Response.json({
        type: InteractionResponseType.CHANNEL_MESSAGE_WITH_SOURCE,
        data: {
          embeds: [
            {
              title: "Example Embed",
              description: "This is an embed generated by your bot.",
              color: 0x5865f2,
            },
          ],
        },
      });
    }

    return Response.json({
      type: InteractionResponseType.CHANNEL_MESSAGE_WITH_SOURCE,
      data: {
        content: "❌ Error: Unknown command.",
      },
    });
  }

  return new Response("OK");
});
